<a href="https://colab.research.google.com/github/zugzwang03/Machine-Learning-Materials/blob/main/activation_functions_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# implementing rectified linear unit using Pytorch
# rules are f(x) = x for x > 0;
#           f(x) = 0 for x <= 0

# f(x) = max(0, x)

import torch
import torch.nn as nn

r = nn.ReLU()

input = torch.tensor([1, 0, -1, 2])

output = r(input)

print(output)

tensor([1, 0, 0, 2])


In [6]:
# leaky ReLU
# f(x) = max(0, x) + negative_slope * min(0, x)

import torch
import torch.nn as nn

input = torch.Tensor([1, 2, -2, 0])
lr = nn.LeakyReLU(0.2)
output = lr(input)

print(output)

tensor([ 1.0000,  2.0000, -0.4000,  0.0000])


In [10]:
# sigmoid function
# f(x) = 1 / (1 + e^-x)
# vanishing gradient
# (0, 1)

import torch
import torch.nn as nn

input = torch.Tensor([1, 9, -2, 5])
s = nn.Sigmoid()
output = s(input)

print(output)

tensor([0.7311, 0.9999, 0.1192, 0.9933])


In [11]:
# tanh
# f(x) = (e^x - e^(-x)) / (e^x + e^(-x))
# vanishing gradient
# (-1, 1)
# pass through 0 or origin but slow

import torch
import torch.nn as nn

input = torch.Tensor([1, 0, -2, 9])
t = nn.Tanh()
output = t(input)

print(output)

tensor([ 0.7616,  0.0000, -0.9640,  1.0000])


In [12]:
# softmax
# f(x) = (e^x) / summation(e^x)
# normalizing the output in probabilistic form
# (0, 1)
# sum = 1

import torch
import torch.nn as nn

input = torch.Tensor([1, 0, -2, 9])
sm = nn.Softmax(dim = 0)
output = sm(input)

print(output)

tensor([3.3530e-04, 1.2335e-04, 1.6694e-05, 9.9952e-01])
