<a href="https://colab.research.google.com/github/zugzwang03/Machine-Learning-Materials/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
my_lst = [1, 2, 3, 4, 5]

arr = np.array(my_lst);
arr

array([1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.shape

(5,)

In [ ]:
print(arr)

[1 2 3 4 5]


In [ ]:
lst1 = [1, 2, 3]
lst2 = [4, 5, 6]

lst = np.array([lst1, lst2])
lst

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
lst.shape

(2, 3)

In [ ]:
lst

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
lst[0:1, 0:2]

array([[1, 2]])

In [ ]:
np.arange(0, 3, 1)

array([0, 1, 2])

In [ ]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
arr1 = np.array(lst1)
arr1[1:] = 3
arr1

array([1, 3, 3])

In [ ]:
arr1 < 2
arr1[arr1 >= 2]

array([3, 3])

In [ ]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [ ]:
np.random.rand(3, 3)

array([[0.93790504, 0.09138698, 0.75620645],
       [0.18551992, 0.20572842, 0.7490934 ],
       [0.1210806 , 0.5974326 , 0.13568962]])

In [ ]:
np.random.randn(4, 4)

array([[ 0.08774049, -0.06931347, -0.3745467 , -0.91061526],
       [-0.06951604, -1.43066755, -0.99156079,  0.52707691],
       [ 0.13998795, -1.44164994,  0.59001491, -1.45804607],
       [-1.08243413,  0.44548602,  1.67721706,  0.85981545]])